const ADD_CHARACTER_TO_FAVORITE = "ADD_CHARACTER_TO_FAVORITE";
const REMOVE_CHARACTER_FROM_FAVORITE = "REMOVE_CHARACTER_FROM_FAVORITE";

export default { ADD_CHARACTER_TO_FAVORITE, REMOVE_CHARACTER_FROM_FAVORITE };
